# CometBFT Configuration for validator-4

proxy_app = "tcp://node-4:26658"
moniker = "validator-4"

[rpc]
laddr = "tcp://0.0.0.0:26657"
cors_allowed_origins = ["*"]

[p2p]
laddr = "tcp://0.0.0.0:26656"
persistent_peers = "eef41000df0f2744c39f7aa86106be326bd7202a@cometbft-0:26656,569feeac2d5e892dcff80b0018c30aed6c00681d@cometbft-1:26656,c3d780e9babbd9c57cc3510d9f072dee97283953@cometbft-2:26656,541b84504711d55e2e28398a529654b0b621c814@cometbft-3:26656"
addr_book_file = "data/addrbook.json"
addr_book_strict = false
allow_duplicate_ip = true

[mempool]
size = 5000
cache_size = 10000

[consensus]
timeout_propose = "1s"
timeout_propose_delta = "500ms"
timeout_prevote = "1s"
timeout_prevote_delta = "500ms"
timeout_precommit = "1s"
timeout_precommit_delta = "500ms"
timeout_commit = "1s"

[statesync]
enable = false

[instrumentation]
prometheus = true
prometheus_listen_addr = ":26660"
